project:
  type: website
  output-dir: docs
  resources:
    - html/*
    - help/*
    - NEWS.html
    - Governance.md
    - R.css
    - vignettes/*

website:
  title: "panelPomp"

  navbar:
    right:
      - icon: github
        aria-label: GitHub
        menu:
          - text: Source Code
            href: https://github.com/panelPomp-org/panelPomp
          - text: Report a Bug
            href: https://github.com/panelPomp-org/panelPomp/issues
    left:
      - href: about.qmd
        text: About
      - href: bibliography.qmd
        text: Bibliography
      - href: html/00Index.html
        text: Manual
      - href: news.qmd
        text: NEWS
      - href: governance.qmd
        text: Contributing
      - text: "Tutorials"
        menu:
          - href: vignettes/getting-started.qmd
            text: "Getting Started"
          - href: vignettes/tutorial.pdf
            text: "Package Tutorial"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


